### ISSUE TITLE
Starting all the services in ubuntu-16.04

### ISSUE THREAD

**Issue by dashohoxha** [solita/docker-systemd#5]
I am using Docker as a light-weight VM. I tried the official image `ubuntu-16.04` but it did not start all the services. Then I came up with the following hack, which somehow works:
(see: https://github.com/dashohoxha/dbox/blob/master/docker/Dockerfile#L1-L12)

```
FROM ubuntu:16.04
ENV container docker
RUN echo '#!/bin/bash\n\
        for service in /etc/rc3.d/S* ; do\n\
            service=$(basename $service)\n\
            service=${service:3}\n\
            /etc/init.d/$service start\n\
        done\n\
        exec /sbin/init\n'\
    > /usr/local/sbin/init.sh
RUN chmod +x /usr/local/sbin/init.sh
CMD ["/usr/local/sbin/init.sh"]
```

Later I discovered `solita/docker-systemd` which looks like more professional, but also seems to me more complex. The previous solution seems to me simpler, it seems to work well so far, and I would like to stick with it if there is nothing fundamentally wrong with it.

What do you think, is it ok to keep using it, or there is something wrong with it?

**Comment by dashohoxha** [comment]
The only problem that I can see until now is that some terminated processes are not closed properly, like this one:

`808 ?        Z      0:00 [ondemand] <defunct>`

I don't know how bad this is, but maybe in some situations it may become a real problem.

**Comment by noidi** [comment]
That's because Bash is not a proper init process. What you're seeing is explained in detail in the article [Docker and the PID 1 zombie reaping problem](https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/).

I'd say that your approach is fine if you use it for development and don't mind restarting your containers now and then. Do note, though, that it only works with init scripts. Now that systemd has become the standard init in all major Linux distributions, more and more services will migrate from init scripts to systemd services and to run them, you'll need systemd. (In fact, `solita/ubuntu-systemd` and `solita/centos-systemd` were created to test our own systemd services and deployment scripts that manage them.)

**Comment by dashohoxha** [comment]
My approach is also neccessary, because systemd and ubuntu-16.04 are only experimental, they do not work as expected. For example I get the problem that is described here: http://askubuntu.com/questions/796651/apache2-fails-to-start-on-boot-with-ubuntu-16-04

I also hope that some day systemd will be improved to be more Docker friendly, so that we don't need to modify the host in order to run a container with the process `/sbin/init`.
