### ISSUE TITLE
docker logs is empty (aka. how to force systemd to log to stdout?)

### ISSUE THREAD

**Issue by PAStheLoD** [solita/docker-systemd#6]
Hello,

I tried to emulate the same setup for 16.10, but there seems to be no output from systemd.

I tried to strace systemd, but it just relentlessly tries to open /dev/console. Which is EIO or ENOSYS.

Then I tried with the 'canonical' image from docker hub, same result, no logs.

**Comment by noidi** [comment]
Thank you for reporting this issue!

It seems that some change made in `ubuntu:xenial-20160914` has broken `solita/ubuntu-systemd` (`ubuntu:xenial-20160818` seems to work). Unfortunately I don't currently use this image so I don't have the time to look deeper into this problem. If someone comes up with a fix, I'd be more than happy to merge it, though!

As a workaround you could build this image against an older version of the `ubuntu` image, or use `solita/centos-systemd`, which hasn't bit-rotted like this.

**Comment by Natorator** [comment]
I have been fighting a bug running systemd inside a Docker container for months - and it started between with  ubuntu:xenial-20160914 also. 

After months of debugging, I finally figured out what it is: the docker run -t option. It so happens, you recommend that in your README, as well, so I wouldn't be surprised if it's biting your project, as well. Try it without -t . 

I usually find I want -t so that when I docker exec -it $container bash, my TERM environment variable is set. But I find that passing docker run -e TERM=xterm works just as well for that, without causing systemd any problems.

**Comment by noidi** [comment]
Thanks for the information, @Natorator. Unfortunately it seems that systemd writes its logs directly to the pseudoterminal and not into stdout/stderr, so leaving out the `-t` still leaves us with no logs (and setting `TERM=xterm` doesn't help).

You are probably right that the `-t` switch is giving systemd some trouble with the problematic base images, because the containers started with `-t` don't shut down cleanly (implying that systemd is stuck).

**Comment by rectalogic** [comment]
It sounds like it's this docker /dev/console bug docker/docker#27202 breaks newer systemd
